apiVersion: v1
kind: Template
metadata:
  name: cve-update-buildconfig
  annotations:
    description: >
            This is Thoth CVE Update CronJob BuildConfig, this template is
            meant to be used by Jenkins, but could also be used by humans...
    openshift.io/display-name: Thoth CVE Update BuildConfig
    version: 0.3.0
    tags: poc,thoth,thoth-cve-update,cve,ai-stacks
    template.openshift.io/documentation-url: https://github.com/AICoE/Thoth/
    template.openshift.io/long-description: >
            This is Thoth CVE update CronJob BuildConfig, this template is
            meant to be used by Jenkins, but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: cve-update-buildconfig
    app: thoth
    component: cve-update

objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        app: thoth
        component: cve-update
      name: cve-update-job
    spec:
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      output:
        to:
          kind: ImageStreamTag
          name: "cve-update-job:${IMAGE_STREAM_TAG}"
      runPolicy: Serial
      source:
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: s2i-thoth-ubi8-py36:latest
          env:
            - name: ENABLE_PIPENV
              value: '1'
            - name: UPGRADE_PIP_TO_LATEST
              value: ''
            - name: "THOTH_DRY_RUN"
              value: "1"
            - name: "THOTH_ADVISE"
              value: "1"
            - name: "THAMOS_VERBOSE"
              value: "1"
            - name: "THAMOS_DEBUG"
              value: "1"
            - name: "THAMOS_CONFIG_TEMPLATE"
              value: ".thothTemplate.yaml"
            - name: "THAMOS_CONFIG_EXPAND_ENV"
              value: "1"
      triggers:
        - imageChange: {}
          type: ImageChange
        - type: "Generic"
          generic:
            secretReference:
              name: generic-webhook-secret
parameters:
  - description: Git repository for Thoth's CVE Update Job
    displayName: Thoth CVE Update Job git repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/cve-update-job'

  - description: Git repository for Thoth's CVE Update Job
    displayName: Thoth cve-update-job git reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
